base_path: .
project_id: "503410"
preserve_hierarchy: false
base_url: "https://api.crowdin.com"
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /apps/client/src/locales/en-US/messages.po
    translation: /apps/client/src/locales/%locale%/messages.po
