base_path: .
preserve_hierarchy: 
base_url: 'https://api.crowdin.com'
files:
  - source: /apps/client/src/locales/en-US/messages.po
    translation: /apps/client/src/locales/%locale%/messages.po
bundles:
  - 4
