base_path: .
project_id: "503410"
base_url: https://api.crowdin.com
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: false

files:
  - type: po
    source: /apps/client/src/locales/en-US.po
    translation: /apps/client/src/locales/%locale%.po
