name: Close Stale Issues

on:
  schedule:
    - cron: 0 0 * * * # every day at midnight (UTC)

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v8.0.0
        with:
          stale-issue-message: It seems that there has been no activity on this issue for a while. I decided to mark issues as stale when they haven't had any activity for a certain amount of time to help maintain the project's focus on active problems. It's nothing personal, I just have only so much free time. If you think this issue is still relevant, please comment with a reason why it should be reopened. Thank you for your contributions to the project!
