name: Update Translations

on:
  push:
    branches:
      - v4

jobs:
  update-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Sync Sources with Crowdin
        uses: crowdin/github-action@v1.14.1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false

        env:
          GITHUB_TOKEN: ${{ github.token }}
          CROWDIN_PROJECT_ID: "503410"
          CROWDIN_ACCESS_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
